import Anthropic from '@anthropic-ai/sdk';
import { zodOutputFormat } from '@anthropic-ai/sdk/helpers/zod';
import { CATEGORIES, ExternalApiError, type Category } from '@aoc/core';
import { z } from 'zod';
import { GENERATOR_PROMPTS, type IdeaFocus } from './catalog';
import type { IdeaDraft } from './types';

/**
 * Optional LLM idea generator (Claude). Off unless ANTHROPIC_API_KEY is set
 * and IDEA_GENERATOR_LLM_ENABLED=true. Output is constrained to a schema,
 * every idea is stored as HYPOTHETICAL with origin LLM, and the prompt
 * forbids profit claims. Ideas must still pass research and testing.
 */

const IdeaSchema = z.object({
  ideas: z.array(
    z.object({
      name: z.string(),
      category: z.enum(CATEGORIES),
      description: z.string(),
      revenueSource: z.string(),
      estimatedCapitalUsd: z.number(),
      automation: z.number(),
      complexity: z.number(),
      scalability: z.number(),
      testability: z.number(),
      risks: z.array(z.string()),
      dependencies: z.array(z.string()),
      regulatoryRisks: z.array(z.string()),
      howToTestCheaply: z.string(),
    }),
  ),
});

const SYSTEM = `You help a research lab find automatable online business and trading ideas to TEST in simulation and paper mode.
Rules:
- Never claim or imply guaranteed or likely profits. Describe hypotheses, costs and risks.
- Only ideas that are legal, respect platform terms of service and do not rely on bypassing security, rate limits or access restrictions.
- No spam: any outreach idea must include consent/opt-out handling.
- Prefer ideas that can be tested cheaply with public data or small experiments.
- Scores (automation, complexity, scalability, testability) are integers from 0 to 100.`;

export interface LlmIdeaOptions {
  apiKey: string;
  model: string;
  focus: IdeaFocus;
  count: number;
  existingNames: string[];
  client?: Anthropic;
}

export async function generateLlmIdeas(o: LlmIdeaOptions): Promise<{ ideas: IdeaDraft[]; model: string }> {
  const client = o.client ?? new Anthropic({ apiKey: o.apiKey, maxRetries: 2 });
  const prompt = `${GENERATOR_PROMPTS[o.focus]}
Return ${o.count} distinct ideas. Avoid these existing ideas: ${o.existingNames.slice(0, 80).join('; ') || 'none'}.`;
  const response = await client.beta.messages.parse({
    model: o.model,
    max_tokens: 16000,
    system: SYSTEM,
    messages: [{ role: 'user', content: prompt }],
    output_config: { effort: 'medium', format: zodOutputFormat(IdeaSchema) },
    // On a policy refusal, Anthropic re-runs the request on its recommended fallback model.
    betas: ['server-side-fallback-2026-07-01'],
    fallbacks: 'default',
  });
  if (response.stop_reason === 'refusal') {
    throw new ExternalApiError('HTTP', `idea generator request was declined (${response.stop_details?.category ?? 'unspecified'})`, { source: 'anthropic.messages' });
  }
  const parsed = response.parsed_output;
  if (!parsed) throw new ExternalApiError('MALFORMED', 'idea generator returned no parseable output', { source: 'anthropic.messages' });
  const clamp = (x: number) => Math.max(0, Math.min(100, Math.round(x)));
  const ideas: IdeaDraft[] = parsed.ideas.map((i) => ({
    name: i.name.slice(0, 200),
    category: i.category as Category,
    description: i.description,
    origin: 'LLM',
    estimatedCapital: Math.max(0, i.estimatedCapitalUsd),
    automationScore: clamp(i.automation),
    complexityScore: clamp(i.complexity),
    scalabilityScore: clamp(i.scalability),
    testabilityScore: clamp(i.testability),
    revenueSource: i.revenueSource,
    risks: i.risks,
    dependencies: i.dependencies,
    regulatoryRisks: i.regulatoryRisks,
    suggestedStrategyId: null,
    sources: [],
    notes: [`Generated by ${response.model} (LLM output, unverified). Suggested cheap test: ${i.howToTestCheaply}`],
  }));
  return { ideas, model: response.model };
}
