import type { ResearchItem } from './types';

/**
 * Curated references behind the starter experiments. Summaries are this
 * project's own one-paragraph descriptions, not quotes. Each entry lists the
 * strategy modules it informs.
 */
export interface SeedSource extends ResearchItem {
  informs: string[];
}

export const SEED_SOURCES: SeedSource[] = [
  {
    sourceType: 'PAPER',
    title: 'Time Series Momentum (Moskowitz, Ooi & Pedersen, Journal of Financial Economics, 2012)',
    url: 'https://doi.org/10.1016/j.jfineco.2011.11.003',
    author: 'Tobias J. Moskowitz, Yao Hua Ooi, Lasse Heje Pedersen',
    publishedAt: '2012-05-01',
    summary: 'Documents that an asset’s own past 12-month return predicts its future return across futures markets in many asset classes, and that a diversified time-series momentum strategy earned positive risk-adjusted returns historically.',
    relevantConcept: 'Time-series momentum: trade an asset in the direction of its own past return.',
    advantages: ['Long, multi-asset evidence', 'Simple, low-turnover rule'],
    disadvantages: ['Evidence is mostly monthly horizons in futures, not hourly crypto', 'Returns concentrated in trending regimes'],
    risk: 'Crowding and regime dependence; sharp reversals.',
    implementationIdea: 'Hourly crypto analogue: hold while the trailing return exceeds a threshold; validate with walk-forward on real data.',
    license: null,
    termsConcerns: 'Academic paper; method implemented independently.',
    informs: ['trading.momentum', 'trading.trend-following'],
  },
  {
    sourceType: 'PAPER',
    title: 'Returns to Buying Winners and Selling Losers (Jegadeesh & Titman, Journal of Finance, 1993)',
    url: 'https://doi.org/10.1111/j.1540-6261.1993.tb04702.x',
    author: 'Narasimhan Jegadeesh, Sheridan Titman',
    publishedAt: '1993-03-01',
    summary: 'The classic cross-sectional momentum study on US equities: stocks with high past 3–12 month returns continued to outperform past losers over the following months.',
    relevantConcept: 'Momentum as a persistent anomaly.',
    advantages: ['Foundational, widely replicated'],
    disadvantages: ['Cross-sectional equities, not single-asset crypto'],
    risk: 'Momentum crashes.',
    implementationIdea: 'Background for momentum hypotheses; not directly transferable.',
    license: null,
    termsConcerns: 'Academic paper.',
    informs: ['trading.momentum'],
  },
  {
    sourceType: 'PAPER',
    title: 'Pairs Trading: Performance of a Relative-Value Arbitrage Rule (Gatev, Goetzmann & Rouwenhorst, Review of Financial Studies, 2006)',
    url: 'https://doi.org/10.1093/rfs/hhj020',
    author: 'Evan Gatev, William N. Goetzmann, K. Geert Rouwenhorst',
    publishedAt: '2006-01-01',
    summary: 'Tests a simple pairs-trading rule on US equities (match stocks by price co-movement, trade divergences) and finds historically positive excess returns that declined over time.',
    relevantConcept: 'Relative-value mean reversion between related assets.',
    advantages: ['Market-neutral by construction'],
    disadvantages: ['Profitability decayed in later samples', 'Relationship breaks are costly'],
    risk: 'Structural breaks in the pair relationship.',
    implementationIdea: 'BTC/ETH log-spread with rolling hedge ratio, z-score entries, time stop.',
    license: null,
    termsConcerns: 'Academic paper.',
    informs: ['trading.stat-arb-pairs'],
  },
  {
    sourceType: 'PAPER',
    title: 'High-frequency trading in a limit order book (Avellaneda & Stoikov, Quantitative Finance, 2008)',
    url: 'https://doi.org/10.1080/14697680701381228',
    author: 'Marco Avellaneda, Sasha Stoikov',
    publishedAt: '2008-04-01',
    summary: 'Derives optimal bid and ask quotes for a market maker facing inventory risk: quotes are centred on a reservation price that shifts against the current inventory.',
    relevantConcept: 'Inventory-skewed market making.',
    advantages: ['Principled inventory control'],
    disadvantages: ['Assumes a fill-intensity model that must be calibrated per market'],
    risk: 'Adverse selection is outside the basic model.',
    implementationIdea: 'Skew prediction-market quotes against held inventory; stop quoting near resolution.',
    license: null,
    termsConcerns: 'Academic paper.',
    informs: ['pm.market-making'],
  },
  {
    sourceType: 'PAPER',
    title: 'The Deflated Sharpe Ratio (Bailey & López de Prado, Journal of Portfolio Management, 2014)',
    url: 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2460551',
    author: 'David H. Bailey, Marcos López de Prado',
    publishedAt: '2014-09-01',
    summary: 'Corrects the Sharpe ratio for selection bias from trying many strategy variants and for non-normal returns, giving the probability that the observed performance is not a statistical fluke.',
    relevantConcept: 'Multiple-testing correction for backtests.',
    advantages: ['Directly addresses overfitting from parameter search'],
    disadvantages: ['Needs an honest count of trials'],
    risk: 'Under-counting trials makes the correction too lenient.',
    implementationIdea: 'Strategy Lab only recommends variants whose deflated Sharpe exceeds 0.9 for the number of variants tried.',
    license: null,
    termsConcerns: 'Academic paper.',
    informs: ['*'],
  },
  {
    sourceType: 'PAPER',
    title: 'The Price Impact of Order Book Events (Cont, Kukanov & Stoikov, Journal of Financial Econometrics, 2014)',
    url: 'https://arxiv.org/abs/1011.6402',
    author: 'Rama Cont, Arseniy Kukanov, Sasha Stoikov',
    publishedAt: '2014-01-01',
    summary: 'Shows that short-term price changes are largely explained by order-flow imbalance at the best quotes, with a slope inversely related to market depth.',
    relevantConcept: 'Order-flow / depth imbalance as a short-horizon signal.',
    advantages: ['Simple, well-founded microstructure signal'],
    disadvantages: ['Very short horizon; costs dominate on wide-tick markets'],
    risk: 'Edge smaller than the spread on prediction markets.',
    implementationIdea: 'Depth imbalance on outcome-token books with a fixed holding time.',
    license: null,
    termsConcerns: 'Academic paper.',
    informs: ['pm.orderbook-imbalance'],
  },
  {
    sourceType: 'PAPER',
    title: 'Volatility-Managed Portfolios (Moreira & Muir, Journal of Finance, 2017)',
    url: 'https://doi.org/10.1111/jofi.12513',
    author: 'Alan Moreira, Tyler Muir',
    publishedAt: '2017-08-01',
    summary: 'Scaling exposure inversely to recent realised variance improved Sharpe ratios for many factors historically.',
    relevantConcept: 'Volatility targeting.',
    advantages: ['Reduces exposure in turbulent periods'],
    disadvantages: ['Levers up into calm periods that can precede crashes'],
    risk: 'Volatility regime shifts.',
    implementationIdea: 'Trend-following position size scaled to a target annual volatility.',
    license: null,
    termsConcerns: 'Academic paper.',
    informs: ['trading.trend-following', 'trading.volatility-breakout'],
  },
  {
    sourceType: 'PAPER',
    title: 'The Stationary Bootstrap (Politis & Romano, Journal of the American Statistical Association, 1994)',
    url: 'https://doi.org/10.1080/01621459.1994.10476870',
    author: 'Dimitris N. Politis, Joseph P. Romano',
    publishedAt: '1994-12-01',
    summary: 'A block bootstrap with random block lengths that keeps the resampled series stationary while preserving short-range dependence.',
    relevantConcept: 'Resampling dependent returns for Monte Carlo robustness checks.',
    advantages: ['Respects autocorrelation'],
    disadvantages: ['Mean block length is a tuning choice'],
    risk: 'None for this use.',
    implementationIdea: 'Monte Carlo over period returns for carry strategies with few discrete trades.',
    license: null,
    termsConcerns: 'Academic paper.',
    informs: ['arb.funding-rate'],
  },
  {
    sourceType: 'PAPER',
    title: 'A New Interpretation of Information Rate (Kelly, Bell System Technical Journal, 1956)',
    url: 'https://doi.org/10.1002/j.1538-7305.1956.tb03809.x',
    author: 'J. L. Kelly Jr.',
    publishedAt: '1956-07-01',
    summary: 'Introduces the growth-optimal bet fraction for repeated bets with known odds — the origin of Kelly sizing.',
    relevantConcept: 'Bet sizing under an edge.',
    advantages: ['Maximises long-run growth when probabilities are known'],
    disadvantages: ['Probabilities are estimated in practice; full Kelly on an overconfident model is ruinous'],
    risk: 'Model error.',
    implementationIdea: 'Fractional Kelly for prediction-market value trades.',
    license: null,
    termsConcerns: 'Academic paper.',
    informs: ['pm.value'],
  },
  {
    sourceType: 'API_DOCS',
    title: 'Polymarket developer documentation',
    url: 'https://docs.polymarket.com',
    author: 'Polymarket',
    summary: 'Official documentation for the Gamma (market metadata), CLOB (order books, orders) and Data APIs and the market WebSocket. This repository’s services/pmbot/docs/API.md records the endpoints verified against the official client.',
    relevantConcept: 'Prediction-market data source.',
    advantages: ['Public read-only market data without credentials'],
    disadvantages: ['Geographic restrictions on trading'],
    risk: 'Terms and fee schedules change; verify before relying on them.',
    implementationIdea: 'Read-only market snapshots for paper testing.',
    license: null,
    termsConcerns: 'Follow the API terms and rate limits; no circumvention of access restrictions.',
    informs: ['pm.arbitrage', 'pm.market-making', 'pm.mispricing', 'pm.value', 'pm.orderbook-imbalance', 'pm.near-resolution'],
  },
  {
    sourceType: 'API_DOCS',
    title: 'Binance Spot API — market data endpoints',
    url: 'https://developers.binance.com/docs/binance-spot-api-docs/rest-api/market-data-endpoints',
    author: 'Binance',
    summary: 'Kline, depth and ticker endpoints with request-weight limits; data-api.binance.vision serves public market data only.',
    relevantConcept: 'Historical bars and live books for crypto backtests and paper trading.',
    advantages: ['Long free history', 'High liquidity'],
    disadvantages: ['Not available in every jurisdiction'],
    risk: 'Endpoint/limit changes.',
    implementationIdea: 'Klines for backtests, depth/bookTicker for paper fills.',
    license: null,
    termsConcerns: 'Respect the API terms and rate limits.',
    informs: ['trading.momentum', 'trading.mean-reversion', 'trading.breakout', 'trading.trend-following', 'trading.volatility-breakout', 'arb.cross-exchange'],
  },
  {
    sourceType: 'API_DOCS',
    title: 'Binance USDⓈ-M Futures — funding rate history',
    url: 'https://developers.binance.com/docs/derivatives/usds-margined-futures/market-data/rest-api/Get-Funding-Rate-History',
    author: 'Binance',
    summary: 'Historical funding rates (fundingRate, fundingTime, markPrice) per perpetual symbol, up to 1000 rows per request.',
    relevantConcept: 'Funding carry data.',
    advantages: ['Complete funding history'],
    disadvantages: ['Shared rate limit for the endpoint'],
    risk: 'Funding formula changes.',
    implementationIdea: 'Backtest cash-and-carry entries and exits on real funding prints.',
    license: null,
    termsConcerns: 'Respect the API terms.',
    informs: ['arb.funding-rate', 'trading.stat-arb-pairs'],
  },
  {
    sourceType: 'GITHUB',
    title: 'hummingbot/hummingbot',
    url: 'https://github.com/hummingbot/hummingbot',
    repository: 'hummingbot/hummingbot',
    author: 'Hummingbot Foundation',
    summary: 'Open-source framework for market-making and arbitrage bots across many exchanges.',
    relevantConcept: 'Market-making and cross-exchange arbitrage strategy structure.',
    advantages: ['Mature, actively maintained, many connectors'],
    disadvantages: ['Large codebase; live-trading oriented'],
    risk: 'Using it live is out of scope for this platform.',
    implementationIdea: 'Conceptual reference for inventory skew and cross-venue arbitrage; no code copied.',
    license: 'Apache-2.0',
    termsConcerns: 'Apache-2.0 is permissive, but this project implements its own logic and does not copy code.',
    informs: ['pm.market-making', 'arb.cross-exchange'],
  },
  {
    sourceType: 'GITHUB',
    title: 'freqtrade/freqtrade',
    url: 'https://github.com/freqtrade/freqtrade',
    repository: 'freqtrade/freqtrade',
    author: 'freqtrade',
    summary: 'Open-source crypto trading bot with backtesting, hyper-parameter optimisation and dry-run (paper) mode.',
    relevantConcept: 'Strategy interface, backtesting and dry-run separation.',
    advantages: ['Large community', 'Dry-run mode'],
    disadvantages: ['Hyper-parameter optimisation invites overfitting if used blindly'],
    risk: 'n/a (reference only).',
    implementationIdea: 'Inspiration for the strategy lifecycle; this platform adds deflated-Sharpe selection.',
    license: 'GPL-3.0',
    termsConcerns: 'GPL-3.0 is copyleft: conceptual inspiration only, no code copied.',
    informs: ['trading.momentum', 'trading.mean-reversion'],
  },
  {
    sourceType: 'REGULATION',
    title: 'CAN-SPAM Act: A Compliance Guide for Business (US FTC)',
    url: 'https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business',
    author: 'US Federal Trade Commission',
    summary: 'US rules for commercial email: no deceptive headers or subject lines, identify the message as an ad, include a physical address and a working opt-out honoured promptly.',
    relevantConcept: 'Outreach compliance (US).',
    advantages: ['Clear requirements'],
    disadvantages: ['US only; EU rules are stricter'],
    risk: 'Penalties per violating email.',
    implementationIdea: 'Opt-out and suppression list modelled in every outreach experiment.',
    license: null,
    termsConcerns: 'Legal guidance; not legal advice.',
    informs: ['business.ai-lead-generation', 'business.ai-sales-agent'],
  },
  {
    sourceType: 'REGULATION',
    title: 'Gesetz gegen den unlauteren Wettbewerb (UWG) § 7 — Unzumutbare Belästigungen',
    url: 'https://www.gesetze-im-internet.de/uwg_2004/__7.html',
    author: 'Bundesrepublik Deutschland',
    summary: 'German unfair-competition law on unacceptable nuisance: advertising by email generally requires the recipient’s prior express consent, with a narrow exception for existing customers.',
    relevantConcept: 'Outreach compliance (Germany).',
    advantages: [],
    disadvantages: ['Severely limits cold email in Germany'],
    risk: 'Cease-and-desist letters and damages.',
    implementationIdea: 'German-market outreach must be consent-based; flagged in compliance.',
    license: null,
    termsConcerns: 'Legal text; not legal advice.',
    informs: ['business.ai-lead-generation', 'business.ai-sales-agent'],
  },
  {
    sourceType: 'REGULATION',
    title: 'Regulation (EU) 2016/679 — General Data Protection Regulation',
    url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
    author: 'European Union',
    summary: 'EU data-protection law: lawful basis for processing, data-subject rights, processor agreements, transfers.',
    relevantConcept: 'Personal data in support, sales and lead-generation services.',
    advantages: [],
    disadvantages: ['Compliance overhead'],
    risk: 'Fines and loss of client trust.',
    implementationIdea: 'DPA and data-minimisation steps in the compliance checklist.',
    license: null,
    termsConcerns: 'Legal text; not legal advice.',
    informs: ['business.ai-lead-generation', 'business.ai-sales-agent', 'business.ai-support-agent', 'business.ai-saas'],
  },
  {
    sourceType: 'WEBSITE',
    title: 'Anthropic API pricing',
    url: 'https://www.anthropic.com/pricing',
    author: 'Anthropic',
    summary: 'Published per-token prices for Claude models — an input for the API-cost assumptions of AI service experiments.',
    relevantConcept: 'Variable cost of AI features.',
    advantages: ['Public'],
    disadvantages: ['Per-ticket/email cost depends on prompt size, which is an assumption'],
    risk: 'Price changes.',
    implementationIdea: 'Use to bound the API-cost-per-unit assumptions; replace with measured usage.',
    license: null,
    termsConcerns: 'n/a',
    informs: ['business.ai-support-agent', 'business.ai-saas', 'business.ai-sales-agent', 'business.ai-lead-generation', 'business.digital-products'],
  },
];
